# -*- coding: utf-8 -*-
"""BMI_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16C4-IgTDaujG_RnZ7Le02C5sfp7ZXHXZ
"""

print("Welcome to BMI Calculator!!")

weight =int(input("What is your weight (kg)"))

height =float(input("What is your height (m)"))

BMI = round(weight/(height**2) , 2)

print(f"Your BMI is = {BMI}")